### ISSUE TITLE
[Feature Request] Player name

### ISSUE THREAD

**Issue by manashard** [RealMegaMinds/ActionInventoryMod#10]
Is it possible to add some sort custom selector like [player] or {player}?
Using @p(proximity) is not suitable in some cases.

`[player]` selector will be replaced for the player name who clicked
An example usage:

```json
"action": {
        "actions": [
          {
            "command": "/give [player] diamond",
            "fromServer": true,
            "type": "Command"
          },
          {
            "type": "CloseGui"
          }
        ],
        "type": "Require"
      },

**Comment by Hoid2** [comment]
Does the self selector `@s` work for this?

**Comment by Hoid2** [comment]
Version [3.4.0](https://modrinth.com/mod/actioninventory/version/3.4.0%2B1.19.3) adds support for PlaceHolder Api. You should be able to use the player name with %player:name%
