### ISSUE TITLE
[Feature Request] Provide example datapacks

### ISSUE THREAD

**Issue by GhostIsBeHere** [RealMegaMinds/ActionInventoryMod#11]
I'm a little confused on how to use the mod, and I would like to have an example datapack that contains one or more completed GUIs that I can work off of. Could you make one and put a link to it in the wiki?

**Comment by Hoid2** [comment]
There's an example on the bottom of the [Data Packs v3](https://github.com/RealMegaMinds/ActionInventoryMod/wiki/Data-Packs-v3) page.

**Comment by GhostIsBeHere** [comment]
I guess I'm just blind lol :)
