### ISSUE TITLE
Some placeholder apis work abnormally

### ISSUE THREAD

**Issue by half-nothing** [RealMegaMinds/ActionInventoryMod#13]
Hello,I have a little problem when using your mod.
This placeholder api does not work, what happened?
![image](https://github.com/RealMegaMinds/ActionInventoryMod/assets/50048293/d68b6682-1302-436f-af63-d1bdf98ad72f)
![image](https://github.com/RealMegaMinds/ActionInventoryMod/assets/50048293/6e8e0c5c-5cad-4e28-bbc9-ab35b255a4e9)
So, what can I do to solve this problem?
![image](https://github.com/RealMegaMinds/ActionInventoryMod/assets/50048293/ce703efd-c60b-4d92-9d89-8c8c80e42d46)

mod version: actioninventory-3.4.1+1.20
placeholder version: placeholder-api-2.1.1+1.20

All right, I look your commit [`44ae607`](https://github.com/RealMegaMinds/ActionInventoryMod/commit/44ae607ec6e52f72b357f4277f97620781b1e634)
It looks like you didn't replace placeholderApi for customNbt, just replace for customName?

**Comment by half-nothing** [comment]
The head picture
![image](https://github.com/RealMegaMinds/ActionInventoryMod/assets/50048293/2997afb1-18ab-424c-913b-57305d4ded7a)

**Comment by Hoid2** [comment]
Currently placeholder api is only used for:
* titles
* item name and lore
* GiveAction items
* Messages and commands

But I'll add support for the custom nbt too.

**Comment by half-nothing** [comment]
> Currently placeholder api is only used for:
> 
> * titles
> * item name and lore
> * GiveAction items
> * Messages and commands
> 
> But I'll add support for the custom nbt too.

Thank you for your explanation.
Btw, may I clone your repositories to implement this function, ~~because I am free~~ because time is tight

**Comment by Hoid2** [comment]
Try this version https://modrinth.com/mod/actioninventory/version/3.5.0+1.20.1

**Comment by half-nothing** [comment]
Unfortunately, it does not work well.
![image](https://github.com/RealMegaMinds/ActionInventoryMod/assets/50048293/fd04db8d-6db6-4f5a-b9f7-4d28baeca3c5)
![image](https://github.com/RealMegaMinds/ActionInventoryMod/assets/50048293/438a1e7d-684e-417d-9570-bec9035746b3)
![image](https://github.com/RealMegaMinds/ActionInventoryMod/assets/50048293/0545f8c5-d361-45e9-9196-e3e64307ca41)
![image](https://github.com/RealMegaMinds/ActionInventoryMod/assets/50048293/e063373b-04d3-4069-8fdc-9e8c25b4fb69)

**Comment by Hoid2** [comment]
Were there any errors?

**Comment by half-nothing** [comment]
> Were there any errors?

Nothing.

**Comment by Hoid2** [comment]
It appears that the name is correctly changing, just for some reason the texture isn't. It may take me a little while to figure it out.

**Comment by Hoid2** [comment]
I think I figured it out. Could you test this version and let me know? [actioninventory-3.5.0+1.20.1-test.jar](https://file.io/K7vTINOP1LAh)

**Comment by half-nothing** [comment]
> I think I figured it out. Could you test this version and let me know? [actioninventory-3.5.0+1.20.1-test.jar](https://file.io/K7vTINOP1LAh)

Can you send it again?The link timed out.

**Comment by Hoid2** [comment]
You will have to unzip it. Github doesn't allow raw jar files.
[actioninventory-3.5.0+1.20.1-test.zip](https://github.com/RealMegaMinds/ActionInventoryMod/files/11857623/actioninventory-3.5.0%2B1.20.1-test.zip)

**Comment by half-nothing** [comment]
> You will have to unzip it. Github doesn't allow raw jar files. [actioninventory-3.5.0+1.20.1-test.zip](https://github.com/RealMegaMinds/ActionInventoryMod/files/11857623/actioninventory-3.5.0%2B1.20.1-test.zip)

It works well! Thanks a lot.

**Comment by Hoid2** [comment]
"official" version: https://modrinth.com/mod/actioninventory/version/3.5.1+1.20.1
