### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Alex81341** [RealMegaMinds/ActionInventoryMod#15]
Can you create a mod that changes the Inventory GUI location? Thanks!
*like on a picture
![2023-12-17_17 58 04](https://github.com/RealMegaMinds/ActionInventoryMod/assets/87265332/82a2bd62-e0f0-40a7-accd-307b1ad5833f)

**Comment by Hoid2** [comment]
I mostly only do server-side mods and am not currently working on any new projects. If you want someone else to create this mod for you, you can try the [Fabric Discord](https://discord.gg/v6v4pMv) requests channel.
