### ISSUE TITLE
Consume Action

### ISSUE THREAD

**Issue by heykiditsaaron** [RealMegaMinds/ActionInventoryMod#18]
I cannot under any circumstances get the consume action to actually consume an item. Even the example doesn't work. What is the process to make this possible?

**Comment by Hoid2** [comment]
I'll look into it. What version are you using?

**Comment by heykiditsaaron** [comment]
ActionInvetoryMod 3.7.1 for Fabric 1.20.1, downloaded from Modrinth

**Comment by Hoid2** [comment]
Try this version: https://modrinth.com/mod/actioninventory/version/3.7.2+1.20.1
