### ISSUE TITLE
I just want to express my gratitude here

### ISSUE THREAD

**Issue by gxgx202020** [RealMegaMinds/ActionInventoryMod#2]
This is really a great mod
Very useful for some servers that want to define functions
I just want to express my gratitude here

Is it possible to add an item that disappears after use?

**Comment by gxgx202020** [comment]
> 這真的是一個很棒的mod 對於一些想要定義功能的服務器非常有用 我在這裡只是想表達我的謝意
> 
> 請隨時關閉此主題^ ^

**Comment by Hoid2** [comment]
@gxgx202020 
This is now possible in version 3.1. You may also want to check out the other changes in the wiki as a lot changed from v2 to v3.    

Use an item opener and an item consumable in a consume action in an action inventory's open or close action.
