### ISSUE TITLE
Discord Server Request

### ISSUE THREAD

**Issue by Soham52** [RealMegaMinds/ActionInventoryMod#3]
It would be really nice if there was an official discord server to discuss any problems, issues or ideas with other users about this mod.

Also I want thank you very much for making such a wonderful mod

**Comment by Hoid2** [comment]
Done. https://discord.gg/T9gStZXYVX

**Comment by TheSubMatrix** [comment]
> Done. https://discord.gg/T9gStZXYVX

Sorry to bother but I believe that the discord link expired. Any chance I could get a new link?

**Comment by Hoid2** [comment]
https://discord.gg/EJQUh5d9jc
