### ISSUE TITLE
[Question] Using the mod

### ISSUE THREAD

**Issue by skycatminepokie** [RealMegaMinds/ActionInventoryMod#7]
Hello! The docs are really nicely laid out, but it seems to be missing the way you start adding ActionInventory s. Do you make a datapack, or is this mod intended as a library mod? If so, what's the main class to look at?

Thank you!

**Comment by Hoid2** [comment]
It uses datapacks. [wiki page](https://github.com/RealMegaMinds/ActionInventoryMod/wiki/Data-Packs-v3)

**Comment by Hoid2** [comment]
I also added a link in the home page of the wiki to make it more clear.

**Comment by skycatminepokie** [comment]
Ok, thanks!
