### ISSUE TITLE
[Question] Will there be a 1.19 version?

### ISSUE THREAD

**Issue by MrRubberDucky** [RealMegaMinds/ActionInventoryMod#8]
Been using this mod for a while and i've been liking it, can do some cool stuff with it.
Also, just asking out of curiosity since i'm still sitting on 1.18.2

**Comment by Hoid2** [comment]
A 1.19 version is planned, I just haven't had the time. I'll see if I can release an update next week. I'm glad that you like it.

**Comment by Hoid2** [comment]
Version 3.3.0 for 1.19 has been released on [Modrinth](https://modrinth.com/mod/actioninventory/version/3.3.0). Report any errors you find (because I'm sure they're there).
