### ISSUE TITLE
[Suggestion]You can add placeholder api

### ISSUE THREAD

**Issue by mocksonline** [RealMegaMinds/ActionInventoryMod#9]
Most of the server's menu plug-ins support placeholder api, and fabric also has its own placeholder api, which can be added
https://github.com/Patbox/TextPlaceholderAPI

Just a suggestion

**Comment by mocksonline** [comment]
Display as lore or items name

**Comment by Hoid2** [comment]
I will take a look into adding this.

**Comment by Hoid2** [comment]
Now added in version [3.4.0](https://modrinth.com/mod/actioninventory/version/3.4.0%2B1.19.3)
